Repository getlago/lago-api, pull requests merged in 2022-08, with the labels that each got.

#356 feat: Add Wallet Consumed Amount
  app/graphql/resolvers/wallets_resolver.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/wallets/object.rb
  db/migrate/20220801101144_add_consumed_amount_to_wallets.rb
  db/schema.rb
  schema.graphql
  schema.json
Labels: enhancement, Wallet

#366 feat: Bill anniversary subscriptions
  app/services/billing_service.rb
  spec/services/billing_service_spec.rb
Labels: Subscription

#369 fix: remove result raises error on result not success
  app/jobs/events/create_job.rb
  spec/jobs/events/create_job_spec.rb
Labels: Worker, 🐞 bug

#372 fix(current_usage): Fix customer current usage in API when not found
  app/controllers/api/v1/customers_controller.rb
  app/services/invoices/customer_usage_service.rb
  spec/requests/api/v1/customers_spec.rb
Labels: API, Customers, 🐞 bug

#378 fix: Fix boundaries for full period payed in advance
  app/services/fees/subscription_service.rb
  spec/services/fees/subscription_service_spec.rb
Labels: Subscription, Invoice, 🐞 bug

#379 fix(stripe): ensure payment method is up to date
  app/jobs/payment_providers/stripe/refresh_webhook_job.rb
  app/services/invoices/payments/stripe_service.rb
  app/services/payment_provider_customers/stripe_service.rb
  app/services/payment_providers/stripe_service.rb
  db/migrate/20220811155332_refresh_stripe_webhooks.rb
  db/schema.rb
  lib/tasks/stripe.rake
  spec/fixtures/stripe/payment_method_detached_event.json
  spec/jobs/payment_providers/stripe/refresh_webhook_job_spec.rb
  spec/services/invoices/payments/stripe_service_spec.rb
  spec/services/payment_provider_customers/stripe_service_spec.rb
  spec/services/payment_providers/stripe_service_spec.rb
Labels: Invoice, 🐞 bug

#380 feat: Allow alternate S3 compatible storages
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/storage.yml
Labels: enhancement, Invoice, Infrastructure

#381 fix(customer): Fix removal of stripe customer id
  app/services/customers/update_service.rb
  app/services/payment_provider_customers/create_service.rb
  spec/services/customers/update_service_spec.rb
Labels: Customers, 🐞 bug

#383 feat(free-units): Calculate running total on sum aggregation
  app/services/billable_metrics/aggregations/base_service.rb
  app/services/billable_metrics/aggregations/count_service.rb
  app/services/billable_metrics/aggregations/max_service.rb
  app/services/billable_metrics/aggregations/sum_service.rb
  app/services/billable_metrics/aggregations/unique_count_service.rb
  app/services/fees/charge_service.rb
  spec/services/billable_metrics/aggregations/max_service_spec.rb
  spec/services/billable_metrics/aggregations/sum_service_spec.rb
  spec/services/billable_metrics/aggregations/unique_count_service_spec.rb
Labels: feature

#387 misc: Add Docker Compose file for CI purposes
  docker-compose.ci.yml
Labels: enhancement, Infrastructure

#385 feat: Add pay in advance logic into date service
  app/services/subscriptions/dates/monthly_service.rb
  app/services/subscriptions/dates/weekly_service.rb
  app/services/subscriptions/dates/yearly_service.rb
  app/services/subscriptions/dates_service.rb
  spec/services/subscriptions/dates/monthly_service_spec.rb
  spec/services/subscriptions/dates/weekly_service_spec.rb
  spec/services/subscriptions/dates/yearly_service_spec.rb
  spec/services/subscriptions/dates_service_spec.rb
Labels: feature, Subscription, Invoice

#391 misc: Add CORS origin env var for CI docker compose
  docker-compose.ci.yml
Labels: enhancement, Infrastructure

#396 misc: remove useless Rails credentials system
  .gitignore
  config/credentials.yml.enc
  config/credentials/development.yml.enc
  config/credentials/staging.yml.enc
  config/credentials/test.yml.enc
Labels: enhancement, Infrastructure

#397 misc: Add Redis in CI compose
  docker-compose.ci.yml
Labels: enhancement, Infrastructure

#394 feat: Add validation logic for the volume charge model
  app/models/charge.rb
  app/services/charges/validators/volume_service.rb
  config/locales/en.yml
  schema.graphql
  schema.json
  spec/factories/charge_factory.rb
  spec/models/charge_spec.rb
  spec/services/charges/validators/volume_service_spec.rb
Labels: Plan

#364 feat: Expose billing time into GraphQL queries and mutations
  app/graphql/mutations/subscriptions/create.rb
  app/graphql/types/subscriptions/billing_time_enum.rb
  app/graphql/types/subscriptions/object.rb
  app/services/subscriptions/create_service.rb
  schema.graphql
  schema.json
  spec/graphql/mutations/subscriptions/create_spec.rb
  spec/services/subscriptions/create_service_spec.rb
Labels: Subscription

#389 feat: Use date service for invoice bounds
  app/graphql/types/invoices/object.rb
  app/graphql/types/subscriptions/object.rb
  app/models/invoice.rb
  app/models/invoice_subscription.rb
  app/models/subscription.rb
  app/services/fees/charge_service.rb
  app/services/fees/subscription_service.rb
  app/services/invoices/create_service.rb
  app/services/invoices/customer_usage_service.rb
  app/services/subscriptions/dates/monthly_service.rb
  app/services/subscriptions/dates/weekly_service.rb
  app/services/subscriptions/dates/yearly_service.rb
  app/services/subscriptions/dates_service.rb
  app/views/templates/invoice.slim
  schema.graphql
  schema.json
  spec/models/invoice_subscription_spec.rb
  spec/models/subscription_spec.rb
  spec/services/fees/charge_service_spec.rb
  spec/services/fees/subscription_service_spec.rb
  spec/services/invoices/create_service_spec.rb
  spec/services/invoices/customer_usage_service_spec.rb
  spec/services/subscriptions/dates/monthly_service_spec.rb
  spec/services/subscriptions/dates/weekly_service_spec.rb
  spec/services/subscriptions/dates/yearly_service_spec.rb
Labels: Subscription, Invoice

#392 Remove plan charge currency
  app/controllers/api/v1/plans_controller.rb
  app/graphql/types/charges/input.rb
  app/graphql/types/charges/object.rb
  app/graphql/types/charges/usage.rb
  app/models/charge.rb
  app/serializers/v1/charge_serializer.rb
  app/serializers/v1/charge_usage_serializer.rb
  app/services/fees/charge_service.rb
  app/services/plans/create_service.rb
  db/migrate/20220818151052_remove_amount_currency_null_constraint_from_charges.rb
  db/schema.rb
  schema.graphql
  schema.json
  spec/factories/charge_factory.rb
  spec/graphql/mutations/plans/create_spec.rb
  spec/graphql/mutations/plans/update_spec.rb
  spec/graphql/resolvers/customers/usage_resolver_spec.rb
  spec/requests/api/v1/plans_spec.rb
  spec/serializers/v1/charge_serializer_spec.rb
  spec/services/plans/create_service_spec.rb
  spec/services/plans/update_service_spec.rb
Labels: enhancement

#406 fix: LAGO_USE_AWS_S3 env var usage
  config/environments/production.rb
Labels: Infrastructure, 🐞 bug

#404 feat: Implement volume pricing charge model logic
  app/services/charges/charge_models/volume_service.rb
  app/services/fees/charge_service.rb
  spec/factories/charge_factory.rb
  spec/services/charges/charge_models/volume_service_spec.rb
Labels: Billable metrics

#408 fix(free-units): Includes all the events in running total
  app/services/billable_metrics/aggregations/base_service.rb
  app/services/billable_metrics/aggregations/count_service.rb
  app/services/billable_metrics/aggregations/max_service.rb
  app/services/billable_metrics/aggregations/sum_service.rb
  app/services/billable_metrics/aggregations/unique_count_service.rb
  app/services/charges/charge_models/percentage_service.rb
  app/services/fees/charge_service.rb
  spec/services/billable_metrics/aggregations/sum_service_spec.rb
  spec/services/charges/charge_models/percentage_service_spec.rb
Labels: 🐞 bug

#407 feat: add Organization Name in Segment Identify
  app/jobs/segment_identify_job.rb
  spec/jobs/segment_identify_job_spec.rb
Labels: enhancement

#405 feat: Update GraphQL schema to create or update charges
  app/graphql/concerns/charge_model_attributes_handler.rb
  app/graphql/types/charges/input.rb
  app/graphql/types/charges/object.rb
  app/graphql/types/charges/volume_range.rb
  app/graphql/types/charges/volume_range_input.rb
  schema.graphql
  schema.json
  spec/graphql/mutations/plans/create_spec.rb
  spec/graphql/mutations/plans/update_spec.rb
Labels: Billable metrics

#410 fix: Update lago documentation url
  CONTRIBUTING.md
Labels: documentation

#411 fix: Hotfix subscription index
  app/controllers/api/v1/subscriptions_controller.rb
Labels: 🐞 bug

#412 fix(charge): Prevent issue with plan create/update and empty charges
  app/controllers/api/v1/plans_controller.rb
  spec/requests/api/v1/plans_spec.rb
Labels: Plan, 🐞 bug

#413 feat: add Currency at Customer level for GraphQL
  app/graphql/types/customers/single_object.rb
  schema.graphql
  schema.json
  spec/graphql/resolvers/customer_resolver_spec.rb
Labels: enhancement, GraphQL

#416 misc: Add email for segment identify on self hosted
  app/jobs/segment_identify_job.rb
  spec/jobs/segment_identify_job_spec.rb
Labels: enhancement

#422 fix: Subscription anniversary date with trial amount
  app/services/fees/subscription_service.rb
  spec/services/fees/subscription_service_spec.rb
Labels: Subscription, 🐞 bug
