Repository getlago/lago-api, pull requests merged in 2024-05, with the labels that each got.

#1980 fix(charge_filter): Fix fee breakdown with filter
  app/models/invoice.rb
  spec/models/invoice_spec.rb
Labels: 🐞 Bug

#2007 feat(wallet): Accept negative values for threshold_credits
  app/services/validators/decimal_amount_service.rb
  app/services/wallets/validate_recurring_transaction_rules_service.rb
  app/services/wallets/validate_service.rb
  spec/services/wallets/validate_service_spec.rb
Labels: Wallet

#2028 fix(events): Fix event serialize when not saved in PG
  app/serializers/v1/event_serializer.rb
Labels: 🐞 Bug

#2040 misc: membership role cannot be null
  app/graphql/types/membership_type.rb
  schema.graphql
  schema.json
  spec/graphql/types/membership_type_spec.rb
Labels: GraphQL

#2048 feat(wallet): Do not refresh wallets balance without cache
  clock.rb
Labels: Wallet

#2060 bug: admin_count should count active memberships
  app/graphql/types/memberships/metadata.rb
  spec/graphql/resolvers/memberships_resolver_spec.rb
Labels: 🐞 Bug

#2083 feat(wallet): Extract creation of wallet transaction rule
  app/services/wallets/create_service.rb
  app/services/wallets/recurring_transaction_rules/create_service.rb
  spec/services/wallets/create_service_spec.rb
  spec/services/wallets/recurring_transaction_rules/create_service_spec.rb
Labels: Wallet
