Repository getlago/lago-api, pull requests merged in 2024-12, with the labels that each got.

#2903 feat: rubocop
  app/graphql/types/credit_notes/object.rb
Labels: 🐞 Bug

#2934 fix: Ensure consistent order of results on list responses (frontend and API)
  app/controllers/api/v1/add_ons_controller.rb
  app/controllers/api/v1/billable_metrics_controller.rb
  app/controllers/api/v1/coupons_controller.rb
  app/controllers/api/v1/credit_notes_controller.rb
  app/controllers/api/v1/customers_controller.rb
  app/controllers/api/v1/plans_controller.rb
  app/controllers/api/v1/taxes_controller.rb
  app/controllers/api/v1/wallets_controller.rb
  app/controllers/api/v1/webhook_endpoints_controller.rb
  app/queries/add_ons_query.rb
  app/queries/applied_coupons_query.rb
  app/queries/base_query.rb
  app/queries/billable_metrics_query.rb
  app/queries/coupons_query.rb
  app/queries/credit_notes_query.rb
  app/queries/customers_query.rb
  app/queries/dunning_campaigns_query.rb
  app/queries/fees_query.rb
  app/queries/integration_collection_mappings_query.rb
  app/queries/integration_items_query.rb
  app/queries/integration_mappings_query.rb
  app/queries/invoices_query.rb
  app/queries/past_usage_query.rb
  app/queries/payment_requests_query.rb
  app/queries/plans_query.rb
  app/queries/subscriptions_query.rb
  app/queries/taxes_query.rb
  app/queries/wallet_transactions_query.rb
  app/queries/wallets_query.rb
  app/queries/webhook_endpoints_query.rb
  app/queries/webhooks_query.rb
  spec/queries/add_ons_query_spec.rb
  spec/queries/applied_coupons_query_spec.rb
  spec/queries/billable_metrics_query_spec.rb
  spec/queries/coupons_query_spec.rb
  spec/queries/credit_notes_query_spec.rb
  spec/queries/customers_query_spec.rb
  spec/queries/dunning_campaigns_query_spec.rb
  spec/queries/integration_collection_mappings_query_spec.rb
  spec/queries/integration_items_query_spec.rb
  spec/queries/integration_mappings_query_spec.rb
  spec/queries/invoices_query_spec.rb
  spec/queries/past_usage_query_spec.rb
  spec/queries/payment_requests_query_spec.rb
  spec/queries/plans_query_spec.rb
  spec/queries/subscriptions_query_spec.rb
  spec/queries/taxes_query_spec.rb
  spec/queries/wallet_transactions_query_spec.rb
  spec/queries/wallets_query_spec.rb
  spec/queries/webhook_endpoints_query_spec.rb
  spec/queries/webhooks_query_spec.rb
  spec/requests/api/v1/plans_controller_spec.rb
Labels: 🐞 Bug

#2966 fix: Ability to create fee with negative units or amount
  app/services/fees/charge_service.rb
  spec/services/fees/charge_service_spec.rb
Labels: 🐞 Bug

#2976 feat(salesforce): Sync with provider always true
  app/services/integration_customers/create_service.rb
  spec/services/integration_customers/create_service_spec.rb
Labels: Customer

#2990 feat: centralize determine payment status
  app/models/payment_providers/adyen_provider.rb
  app/models/payment_providers/base_provider.rb
  app/models/payment_providers/gocardless_provider.rb
  app/models/payment_providers/stripe_provider.rb
  app/services/payment_requests/payments/adyen_service.rb
  app/services/payment_requests/payments/gocardless_service.rb
  app/services/payment_requests/payments/stripe_service.rb
  db/migrate/20241220095049_backfill_payable_payment_status.rb
  db/schema.rb
  spec/factories/payments.rb
  spec/services/payment_requests/payments/adyen_service_spec.rb
  spec/services/payment_requests/payments/gocardless_service_spec.rb
Labels: Payment

#2987 feat(data): Add usage_date to daily_usages
  app/jobs/clock/compute_all_daily_usages_job.rb
  app/jobs/daily_usages/compute_job.rb
  app/models/daily_usage.rb
  app/services/daily_usages/compute_service.rb
  app/services/daily_usages/fill_from_invoice_service.rb
  app/services/daily_usages/fill_history_service.rb
  db/migrate/20241219145642_add_usage_date_to_daily_usages.rb
  db/migrate/20241219152909_add_index_on_usage_date_to_daily_usages.rb
  db/schema.rb
  spec/jobs/clock/compute_all_daily_usages_job_spec.rb
  spec/services/daily_usages/compute_service_spec.rb
  spec/services/daily_usages/fill_from_invoice_service_spec.rb
Labels: Data

#2995 Fix clean duplicate payments
  db/migrate/20241220095049_backfill_payable_payment_status.rb
Labels: 🐞 Bug

#2993 feat(data): Use usage_date instead of refreshed_at for daily usage
  app/models/daily_usage.rb
  app/services/daily_usages/compute_all_service.rb
  app/services/daily_usages/compute_diff_service.rb
  app/services/daily_usages/compute_service.rb
  app/services/daily_usages/fill_from_invoice_service.rb
  app/services/daily_usages/fill_history_service.rb
  spec/factories/daily_usages.rb
  spec/models/daily_usage_spec.rb
  spec/services/daily_usages/compute_all_service_spec.rb
  spec/services/daily_usages/compute_diff_service_spec.rb
  spec/services/daily_usages/compute_service_spec.rb
Labels: Data

#3000 fix(data): Populate daily usages
  app/services/daily_usages/fill_history_service.rb
Labels: Data

#3010 fix: Ensure Plans::DestroyJob are queued only once
  app/jobs/plans/destroy_job.rb
  spec/jobs/plans/destroy_job_spec.rb
Labels: improvement
