Repository getlago/lago-api, pull requests merged in 2025-01, with the labels that each got.

#2972 fix: Persist inbound stripe webhooks
  app/controllers/webhooks_controller.rb
  app/jobs/clock/inbound_webhooks_cleanup_job.rb
  app/jobs/clock/inbound_webhooks_retry_job.rb
  app/jobs/inbound_webhooks/process_job.rb
  app/models/inbound_webhook.rb
  app/services/inbound_webhooks/create_service.rb
  app/services/inbound_webhooks/process_service.rb
  app/services/inbound_webhooks/validate_payload_service.rb
  app/services/payment_providers/stripe/handle_incoming_webhook_service.rb
  app/services/payment_providers/stripe/validate_incoming_webhook_service.rb
  clock.rb
  db/migrate/20241213182343_create_inbound_webhooks.rb
  db/migrate/20241219122151_add_processing_at_to_inbound_webhooks.rb
  db/migrate/20241223154437_add_indices_to_inbound_webhooks.rb
  db/schema.rb
  spec/clockwork_spec.rb
  spec/factories/inbound_webhooks.rb
  spec/jobs/clock/inbound_webhooks_cleanup_job_spec.rb
  spec/jobs/clock/inbound_webhooks_retry_job_spec.rb
  spec/jobs/inbound_webhooks/process_job_spec.rb
  spec/models/inbound_webhook_spec.rb
  spec/requests/webhooks_controller_spec.rb
  spec/services/inbound_webhooks/create_service_spec.rb
  spec/services/inbound_webhooks/process_service_spec.rb
  spec/services/inbound_webhooks/validate_payload_service_spec.rb
  spec/services/payment_providers/stripe/handle_incoming_webhook_service_spec.rb
  spec/services/payment_providers/stripe/validate_incoming_webhook_service_spec.rb
Labels: 🐞 Bug

#3025 fix(fee): Charge pay in advance interval without any day-shift
  app/services/subscriptions/dates_service.rb
Labels: 🐞 Bug, Fee

#3026 fix(fee): Prevent creating fee for an incorrect billing period
  app/services/invoices/advance_charges_service.rb
  spec/services/invoices/advance_charges_service_spec.rb
Labels: 🐞 Bug, Fee

#3027 fix: Retry when getting stale wallet error for pay in advance events
  app/jobs/invoices/create_pay_in_advance_charge_job.rb
Labels: Wallet

#3003 feat: Add payment type and reference
  app/models/invoice.rb
  app/models/payment.rb
  db/migrate/20241224141116_add_payment_type_and_reference_to_payments.rb
  db/migrate/20241224142141_add_total_paid_amount_cents_to_invoices.rb
  db/schema.rb
  spec/factories/payments.rb
  spec/models/payment_spec.rb
Labels: Payment

#3031 feat(manual-payments): Add payment serializer
  app/serializers/v1/payment_serializer.rb
  spec/serializers/v1/payment_serializer_spec.rb
Labels: Payment

#3029 feat(manual-payments): Add service to create manual payments
  app/models/analytics/overdue_balance.rb
  app/models/payment.rb
  app/services/manual_payments/create_service.rb
  config/locales/en.yml
  spec/models/payment_spec.rb
  spec/services/manual_payments/create_service_spec.rb
Labels: Payment

#3012 fix: Recurring fee not displayed on invoices after upgrade
  app/jobs/bill_non_invoiceable_fees_job.rb
  app/services/invoices/advance_charges_service.rb
  app/services/subscriptions/terminate_service.rb
  spec/graphql/lago_api_schema_spec.rb
  spec/scenarios/invoices/recurring_fees_spec.rb
  spec/services/invoices/advance_charges_service_spec.rb
  spec/services/subscriptions/terminate_service_spec.rb
  spec/support/scenarios_helper.rb
Labels: 🐞 Bug

#3034 fix: Use succeeded_at to select fees for regrouping
  app/services/invoices/advance_charges_service.rb
  spec/scenarios/invoices/advance_charges_spec.rb
  spec/services/invoices/advance_charges_service_spec.rb
Labels: 🐞 Bug

#3044 fix: Cast filters to string on ingestion
  app/services/charge_filters/event_matching_service.rb
  spec/services/charge_filters/event_matching_service_spec.rb
Labels: 🐞 Bug

#3054 Add support for filtering invoices by partially paid
  app/controllers/api/v1/invoices_controller.rb
  app/queries/invoices_query.rb
  spec/queries/invoices_query_spec.rb
Labels: Invoice, Payment

#3045 Feat manual payments controller
  app/contracts/queries/payments_query_filters_contract.rb
  app/controllers/api/v1/invoices_controller.rb
  app/controllers/api/v1/payments_controller.rb
  app/models/api_key.rb
  app/models/payment.rb
  app/queries/invoices_query.rb
  app/queries/payments_query.rb
  app/serializers/v1/payment_serializer.rb
  app/services/manual_payments/create_service.rb
  config/routes.rb
  spec/contracts/queries/payments_query_filters_contract_spec.rb
  spec/models/payment_spec.rb
  spec/queries/invoices_query_spec.rb
  spec/queries/payments_query_spec.rb
  spec/requests/api/v1/payments_controller_spec.rb
  spec/serializers/v1/payment_serializer_spec.rb
  spec/services/manual_payments/create_service_spec.rb
Labels: Payment
