Repository getlago/lago-api, pull requests merged in 2025-07, with the labels that each got.

#4002 fix: Abilitiy to filter subscriptions by plan code
  app/queries/subscriptions_query.rb
Labels: 🐞 Bug

#3896 feat(sso_enforcement): Enforce SSO login across my organization
  app/config/permissions/definition.yml
  app/config/permissions/role-finance.yml
  app/config/permissions/role-manager.yml
  app/controllers/concerns/authenticable_user.rb
  app/controllers/graphql_controller.rb
  app/graphql/mutations/integrations/destroy.rb
  app/graphql/mutations/invites/accept.rb
  app/graphql/mutations/organizations/update.rb
  app/graphql/types/organizations/authentication_methods_enum.rb
  app/graphql/types/organizations/current_organization_type.rb
  app/graphql/types/organizations/organization_type.rb
  app/graphql/types/organizations/update_organization_input.rb
  app/mailers/organization_mailer.rb
  app/models/concerns/organizations/authentication_methods.rb
  app/models/integrations/okta_integration.rb
  app/models/organization.rb
  app/models/user.rb
  app/services/auth/google_service.rb
  app/services/auth/okta/accept_invite_service.rb
  app/services/auth/okta/login_service.rb
  app/services/auth/token_service.rb
  app/services/integrations/okta/create_service.rb
  app/services/integrations/okta/destroy_service.rb
  app/services/invites/accept_service.rb
  app/services/organizations/update_service.rb
  app/services/users_service.rb
  app/views/organization_mailer/authentication_methods_updated.slim
  config/locales/en/email.yml
  db/migrate/20250701133139_add_authentication_methods_to_organizations.rb
  db/migrate/20250701141017_set_okta_authentication_method_to_premium_organizations.rb
  db/structure.sql
  schema.graphql
  schema.json
  spec/graphql/mutations/auth/okta/accept_invite_spec.rb
  spec/graphql/mutations/auth/okta/login_spec.rb
  spec/graphql/mutations/integrations/destroy_spec.rb
  spec/graphql/mutations/invites/accept_spec.rb
  spec/graphql/mutations/organizations/update_spec.rb
  spec/graphql/types/organizations/authentication_methods_enum_spec.rb
  spec/graphql/types/organizations/current_organization_type_spec.rb
  spec/graphql/types/organizations/organization_type_spec.rb
  spec/graphql/types/organizations/update_organization_input_spec.rb
  spec/mailers/organization_mailer_spec.rb
  spec/mailers/previews/organization_mailer_preview.rb
  spec/models/concerns/organizations/authentication_methods_spec.rb
  spec/requests/graphql_controller_spec.rb
  spec/services/auth/google_service_spec.rb
  spec/services/auth/okta/accept_invite_service_spec.rb
  spec/services/auth/okta/login_service_spec.rb
  spec/services/auth/token_service_spec.rb
  spec/services/integrations/okta/create_service_spec.rb
  spec/services/integrations/okta/destroy_service_spec.rb
  spec/services/invites/accept_service_spec.rb
  spec/services/organizations/update_service_spec.rb
  spec/services/users_service_spec.rb
Labels: SSO Enforcement

#4066 misc: add invoice payment link generation GQL mutation
  app/graphql/mutations/invoices/generate_payment_url.rb
  app/graphql/types/mutation_type.rb
  schema.graphql
  schema.json
  spec/graphql/mutations/invoices/generate_payment_url_spec.rb
Labels: GraphQL, improvement
